[theme]
base="light"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true

[client]
showErrorDetails = false
toolbarMode = "viewer"

[global]
developmentMode = false

